class Autogenerated {
  String status;
  Data data;

  Autogenerated({this.status, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  List<Food> food;
  int productsTotal;
  int pageTotal;

  Data({this.food, this.productsTotal, this.pageTotal});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['food'] != null) {
      food = [];
      json['food'].forEach((v) {
        food.add(new Food.fromJson(v));
      });
    }
    productsTotal = json['productsTotal'];
    pageTotal = json['pageTotal'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.food != null) {
      data['food'] = this.food.map((v) => v.toJson()).toList();
    }
    data['productsTotal'] = this.productsTotal;
    data['pageTotal'] = this.pageTotal;
    return data;
  }
}

class Food {
  String image;
  int rate;
  String dateCreate;
  String sId;
  String foodName;
  String restaurant;
  int price;
  String caption;
  int iV;

  Food(
      {this.image,
      this.rate,
      this.dateCreate,
      this.sId,
      this.foodName,
      this.restaurant,
      this.price,
      this.caption,
      this.iV});

  Food.fromJson(Map<String, dynamic> json) {
    image = json['image'];
    rate = json['rate'];
    dateCreate = json['dateCreate'];
    sId = json['_id'];
    foodName = json['foodName'];
    restaurant = json['restaurant'];
    price = json['price'];
    caption = json['caption'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['image'] = this.image;
    data['rate'] = this.rate;
    data['dateCreate'] = this.dateCreate;
    data['_id'] = this.sId;
    data['foodName'] = this.foodName;
    data['restaurant'] = this.restaurant;
    data['price'] = this.price;
    data['caption'] = this.caption;
    data['__v'] = this.iV;
    return data;
  }
}
