import 'dart:async';
import 'dart:convert';
import 'package:app_demo_get/productmodule/models/find-all-food.dart';
import 'package:http/http.dart' as http;

class ApiService {
  static Future<List<Food>> fetchFoods() async {
    var url = Uri.https('khtnfoodoffer.herokuapp.com', 'api/cus/findProducts');
    var response = await http.get(url);
    Map<String, dynamic> map = jsonDecode(response.body);
    print(map['status']);
    var test = Autogenerated.fromJson(map);
    print(test.status);
    return test.data.food;
  }
}
